# Generated by Django 3.2.3 on 2021-09-26 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_auto_20210924_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='examiner',
        ),
        migrations.DeleteModel(
            name='MCQ',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
