# Generated by Django 3.2.3 on 2021-09-27 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_mcq_question_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='subject',
        ),
        migrations.DeleteModel(
            name='MCQ',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
