# Generated by Django 3.2.3 on 2021-09-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_mcq_question_questionpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
