# Generated by Django 3.2.3 on 2021-09-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_questionpaper_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='awarded_marks',
            field=models.FloatField(default=0),
        ),
    ]
