# Generated by Django 3.2.3 on 2021-09-30 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_alter_question_awarded_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.FloatField(default=-1)),
                ('question_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.questionpaper')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.test')),
            ],
        ),
    ]
